### ISSUE TITLE
Plugin doesn't work with ojs 3.1.2 (no mail sended)

### ISSUE THREAD

**Issue by Potomac** [jonasraoni/ojs-registration-notification-plugin#2]
Hello,

for the master branch I notice that the plugin doesn't work with OJS 3.1.2, I can install and activate the plugin, I can configure the list of emails, but when a user creates an account then there is no mail sended to the list.

**Comment by jonasraoni** [comment]
Hi @Potomac!
Just a heads up that I've been busy these days, but I'll probably check this today :)

**Comment by jonasraoni** [comment]
@Potomac I've just checked the plugin against the version 3.1.2 and also the master branch, both worked fine in my localhost. So I would say there must be a problem in your configurations.

I suggest you to debug it using xdebug, the entrypoint of the plugin is located in the file RegistrationNotificationPlugin.inc.php:23
