### ISSUE TITLE
How to install this plugin on my OJS 3.0.1.0?

### ISSUE THREAD

**Issue by rubensflinco** [jonasraoni/ojs-registration-notification-plugin#3]
I tried to install it through the administrator panel by uploading the zip file to download the real ones, but it doesn't work. He says he didn't find the folder with the name of the plugin.

And I tried to install the folder directly via FTP but when I go to the list of plugins it doesn't start to load infinitely and the error 500 on the browser console.

Can someone help me?

**Comment by jonasraoni** [comment]
Rubens, esse plugin foi feito para a versão +3.1, então aparentemente vai precisar de algum ajuste para funcionar ai no 3.0... Como o código é minúsculo, acho que não deve ter muita treta.

Enfim, esse repositório foi migrado para cá: https://github.com/pkp/registrationNotification, faz a pergunta lá para ver se há interesse em portar ele para o 3.0, se resolver arrumar sozinho (meu tempo é limitado, tenho 2 filhos + 2 trabalhos kkkkkkk), pode abrir um PR =]

**Comment by rubensflinco** [comment]
ok, muito obrigado eu já vi o outro repositório porem não tem como abrir issues lá não sei por que...
Bom tentarei fazer um downgrade do plugin por conta própria.
