### ISSUE TITLE
OJS 3.2 compatible

### ISSUE THREAD

**Issue by fpessoa** [jonasraoni/ojs-registration-notification-plugin#4]
good morning Jonas, thanks for making your plugin available which is very useful for our control of new users.
But when a new user is registered, I receive a blank email (with my standard signature) and not the template as explained in the readme file. Would it be because of the version I use 3.2 of OJS? Thanks for some updates, greetings

**Comment by jonasraoni** [comment]
Hi @fpessoa! This plugin has been moved to the [PKP organization](https://github.com/pkp/registrationNotification), could you please create this issue there?

Thanks!
